### ISSUE TITLE
Minutes is using month format

### ISSUE THREAD

**Issue by matthewroach** [colin-walker/wordpress-blank-title#1]
Minutes should use `i` not `m` - `m` is for numeric month.

**Comment by colin-walker** [comment]
Ah, stupid mistake. Thanks Matthew.

**Comment by matthewroach** [comment]
Not a problem, I noticed it when I implemented it on my site. Thought quicker making an issue than a PR.. All works good thanks for the code

**Comment by colin-walker** [comment]
Thanks again and glad it works for you.
